// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsqtjhjqytuncpvbnuwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzcXRqaGpxeXR1bmNwdmJudXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODEzNjIsImV4cCI6MjA2NTU1NzM2Mn0.w5QcUnfGDtoKP-iOiv6JSqr79eBb7F2PMd1-Ta8uIYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});